natsort/compat/py23.py

The -OO flag removes docstrings (sets them to None), which caused
issues with the doctoring compatability wrapper because it was trying
to call .format on None.
The wrapper has been modified to check for None.
This should solve issue #38.

Fixed import bug when using python -OO.

---

README.rst
docs/source/howitworks.rst
natsort/ns_enum.py
natsort/utils.py
test_natsort/slow_splitters.py
test_natsort/test_input_string_transform_factory.py
test_natsort/test_natsorted.py
test_natsort/test_utils.py

To minimize astonishment, Unicode data is now normalized to the 'NFD'
normalization form to make the sorting sane. Documentation has been updated
to discuss this where appropriate.
The user has the option of choosing 'NFKD'.

Add normalization to incoming Unicode data

---

natsort/compat/locale.py
natsort/natsort.py
natsort/ns_enum.py
natsort/utils.py
test_natsort/test_final_data_transform_factory.py
test_natsort/test_natsort_key.py
test_natsort/test_natsort_keygen.py
test_natsort/test_natsorted.py
test_natsort/test_parse_number_function.py
test_natsort/test_utils.py

This will close #48, which requests the ability to put numbers after non-numbers, rather than before which is the default.
This was implemented by changing the string separator that is added between or in front of numbers from an empty string to a sequence of high numeric-valued characters when the new option (`ns.NUMAFTER`) is requested.

Add ability to sort numbers after non-numbers

---

natsort/compat/fake_fastnumbers.py
natsort/unicode_numbers.py
natsort/utils.py
test_natsort/slow_splitters.py
test_natsort/test_fake_fastnumbers.py
test_natsort/test_natsorted.py
test_natsort/test_unicode_numbers.py
tox.ini

In order to fully support all numbers that the built-in `int` and `float` support, the regular expressions used to split input strings have been updated to support a wider variety of numbers.
Accepting this will close #52.

Add support for ints and floats comprised of unicode decimal strings.

---

docs/source/howitworks.rst
docs/source/locale_issues.rst

For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html

Update all pypi.python.org URLs to pypi.org

---

README.rst
docs/source/examples.rst
docs/source/howitworks.rst
docs/source/intro.rst
docs/source/locale_issues.rst
docs/source/shell.rst

- Use pycon for Python console.
- Use console for Bash console.
- Use none for --help output
Fixes Sphinx warning of the form:
```
natsort/docs/source/howitworks.rst:176: WARNING: Could not lex literal_block as "python". Highlighting skipped.
natsort/docs/source/howitworks.rst:231: WARNING: Could not lex literal_block as "python". Highlighting skipped.
natsort/docs/source/howitworks.rst:249: WARNING: Could not lex literal_block as "python". Highlighting skipped.
natsort/docs/source/shell.rst:79: WARNING: Could not lex literal_block as "python". Highlighting skipped.
natsort/docs/source/shell.rst:88: WARNING: Could not lex literal_block as "python". Highlighting skipped.
natsort/docs/source/shell.rst:98: WARNING: Could not lex literal_block as "python". Highlighting skipped. …
```

Correct highlighting language in docs

---

docs/source/locale_issues.rst

Fixes Sphinx warning of the form:
```
natsort/docs/source/locale_issues.rst:7: WARNING: Duplicate explicit target name: "pyicu".
natsort/docs/source/locale_issues.rst:7: WARNING: Duplicate explicit target name: "pyicu".
natsort/docs/source/locale_issues.rst:7: WARNING: Duplicate explicit target name: "pyicu".
natsort/docs/source/locale_issues.rst:7: WARNING: Duplicate explicit target name: "pyicu".
```

Consolidate duplicate link names in docs/source/locale_issues.rst

---

docs/howitworks.rst
docs/intro.rst
docs/locale_issues.rst

Automatically builds the correct URL so they do not need to be manually maintained.

Use intershpinx to build links to Python docs

---

tox.ini

Avoids installing the package to the virtualenv before running the
commands. The package is not required to be installed to do simple
static code analysis or build the docs. Results in a slightly faster
run.
For additional information on the configuration option, see:
https://tox.readthedocs.io/en/latest/config.html#confval-skip_install=BOOL
> Do not install the current package. This can be used when you need the
> virtualenv management but do not want to install the current package
> into that environment.

Use skip_install=true for non-testing tox targets

---

README.rst
docs/changelog.rst
docs/intro.rst
natsort/__init__.py
natsort/natsort.py
natsort/ns_enum.py
natsort/utils.py
test_natsort/test_natsorted.py
test_natsort/test_natsorted_convenience.py
test_natsort/test_utils.py

All the deprecated API now has DeprecationWarnings raised, with all the options set appropriately so that users can find where to make changes.
The README and documentation has a nice schedule of when things will be removed, and also suggestions on how to detect deprecated usage.

Formal deprecation notices

---

setup.py

The syntax "fastnumbers >= 2.0.0; python_version > 2.6" is "new" in the
sense that there are still OSs (like CentOS) that use still have
setuptools versions installed that do not support it.
The solution is to selectively add the dependency using logic rather
than declaratively.
This will solve issue #64.

Add support for very old versions of setuptools

---

.travis.yml

Can remove all `sudo` declarations.
Travis officially added support for Xenial on 2018-11-08.
https://blog.travis-ci.com/2018-11-08-xenial-release

Use `dist: xenial` in Travis to simplify configuration

---

README.rst

The CHANGELOG file has the ".md" file extension not ".rst". See:
- https://github.com/SethMMorton/natsort/blob/master/CHANGELOG.rst
- https://github.com/SethMMorton/natsort/blob/master/CHANGELOG.md

CHANGELOG file extension in README.rst

---

README.rst
docs/examples.rst
docs/intro.rst

This PR is against the `drop-python2` branch.

Update docs to remove Python 2

---

.travis.yml

See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

sudo no longer needed

---

.travis.yml
RELEASING.md

This should help make releasing easier.
* Deploy non-tagged builds to Test PyPI
* Deploy tagged builds to live PyPI
Will only trigger when run from the `SethMMorton/natsort` repo, on `master`, so not for forks or PRs.
The `on:` section shows the conditions for triggering an upload. This should be set up so only a single build job qualifies.
Right now, there's only a single Python 3.8 job, so select on `python: 3.8`. If 3.7 and 3.8 are switched, this can also so there's only a single 3.7. It's possible to select on other conditions too:
https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on
`skip_existing: true` should in any case prevent trying to re-upload existing ones.
TODO:
1. Add an API token called (say) `natsort-ci` at https://test.pypi.org/manage/account/token/ …

Deploy to PyPI from Travis CI

---

.travis.yml

I had to disable CI on windows because `choco` stopped working. Let's see if there is a better solution.

Attempt to get Windows CI working again

---

.travis.yml

Travis errorred a couple of times because setting up the build for MacOS failed. I am now using the native python which is not "modern", but I am testing only the locale so this should be fine.

Use native python on MacOS

---

CHANGELOG.md
dev/generate_new_unicode_numbers.py
natsort/unicode_numeric_hex.py
tests/test_unicode_numbers.py
tox.ini

This is intended to close #122.
However, it does not actually address the root cause. It just makes it so that the tests don't fail, and provides an easier and more obvious way for Good Samaritans to perform this upgrade when needed.

Do not fail on new python versions

---

natsort/compat/fastnumbers.py

Distutils is deprecated in Python 3.10 and will be removed in 3.12
Fixes #130

Don't import distutils to check the fastnumbers version.

---

CHANGELOG.md
natsort/utils.py
tests/test_natsorted.py
tests/test_utils.py

Closes #145.
The old algorithm for suffix splitting when applying `PATH` sorting was over-zealous, and it appears to give bad results if filename collections a) have the form "word.then.dot.then.word.then.dot" and b) one or more (but not all) of the filenames looks like "word.then.dot.5.then.dot".
The new algorithm will not attempt to split ALL suffixes, but only the first two it encounters, and then only if the length of the suffix (plus the leading ".") is not more than 5 characters. The rule that the suffix cannot start with the regex `/.\d/` still applies.
---
It's hard to say that this was a "bug" because the algorithm was chosen as it was deliberately, but it certainly was not the desired behavior.

Over zealous extension splitting

---

CHANGELOG.md
MANIFEST.in
mypy_stubs/icu.pyi
natsort/compat/locale.py
natsort/natsort.py
natsort/utils.py
setup.cfg
tests/test_os_sorted.py
tests/test_parse_number_function.py
tox.ini

Closes #154.
This MR aims to make `natsort` functions accept a wider variety of types when type-checking, which is more reflective of reality.

Make typing less strict

---

natsort/natsort.py

See https://github.com/SethMMorton/natsort/issues/157
I ran some benchmarks and I get a consistent 20% improvement when the inputs are `Path` already. Both for small lists and large lists (I tested lists with 10 and 10 000 items).
```python
from random import shuffle
from pathlib import Path
from timeit import repeat
from natsort import os_sorted
INPATH = "<path>"
paths = list(Path(INPATH).rglob("*"))
print(len(paths))
shuffle(paths)
print(min(repeat("os_sorted(paths)", repeat=10, number=1000, globals={"os_sorted": os_sorted, "paths": paths})))
```
I cannot run the test suite sadly since I get lots of `locale.Error: unsupported locale setting` errors.

os_sorted: only convert input to str if necessary

---

CHANGELOG.md
natsort/natsort.py
natsort/utils.py
tests/test_os_sorted.py

It turns out that this is not a behavior that Windows supports - it adds e.g. (2) after the extension, not before, so it does not account for extensions when sorting.

Disable extension splitting on Windows for os_sorted
